// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int biggerThanHalf = 0;
		int smallerThanHalf = 0;
		for (int i = 0; i < n; i++){
			Double randNum = Math.random();
			if (randNum > 0.5) {
				biggerThanHalf ++;
			}
			else {
				smallerThanHalf ++;
			}
		}
		System.out.println("> 0.5:	" + biggerThanHalf + " times");
		System.out.println("<= 0.5:	" + smallerThanHalf + " times");

		if(smallerThanHalf > 0){
			System.out.println("Ratio:	" + (double)biggerThanHalf / (double)smallerThanHalf);
		}
	}
}
